version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    hostname: host.docker.internal
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
