apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ APPNAVN }}
  namespace: teamdigihot
  labels:
    app: {{ APPNAVN }}
    team: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
     - name: JOARK_BASEURL
       value: "{{ JOARK_BASEURL }}"
     - name: JOARK_SCOPE
       value: "{{ JOARK_SCOPE }}"
     - name: KAFKA_CONSUMER_GROUP_ID
       value: "{{ KAFKA_CONSUMER_GROUP_ID }}"
     - name: EVENT_NAME
       value: "{{ EVENT_NAME }}"
     - name: APPNAVN
       value: "{{ APPNAVN }}"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknad-pdfgen
