apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-joark-sink
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 40m
      memory: 512Mi
  env:
  {{#each this}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknad-pdfgen
      external:
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: digihot-proxy.prod-fss-pub.nais.io
