apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-joark-sink
  namespace: teamdigihot
  labels:
    app: hm-joark-sink
    team: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: JOARK_BASEURL
      value: https://digihot-proxy.dev-fss-pub.nais.io/dokarkiv-aad
    - name: JOARK_SCOPE
      value: api://dev-fss.teamdigihot.digihot-proxy/.default
    - name: JOARK_BASEURL_Q1
      value: https://digihot-proxy-q1.dev-fss-pub.nais.io/dokarkiv-aad
    - name: JOARK_SCOPE_Q1
      value: api://dev-fss.teamdigihot.digihot-proxy-q1/.default
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknad-pdfgen
