apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hm-joark-sink
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  env:
  {{#each this}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknad-pdfgen
        - application: hm-pdf-generator
        - application: hm-brev
        - application: hm-soknad-api
      external:
        - host: dokarkiv.dev-fss-pub.nais.io # q1
        - host: dokarkiv-q2.dev-fss-pub.nais.io # q2
        - host: foerstesidegenerator-q1.dev-fss-pub.nais.io # q1
        - host: foerstesidegenerator.dev-fss-pub.nais.io # q2
        - host: saf.dev-fss-pub.nais.io # q1
        - host: saf-q2.dev-fss-pub.nais.io # q2
