apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ appnavn }}
  namespace: teamdigihot
  labels:
    app: hm-joark-sink
    team: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  liveness:
    path: /isalive
    initialDelay: 60
  readiness:
    path: /isready
    initialDelay: 60
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1500Mi
  env:
     - name: JOARK_BASEURL
       value: "{{ JOARK_BASEURL }}"
     - name: JOARK_SCOPE
       value: "{{ JOARK_SCOPE }}"
     - name: KAFKA_CONSUMER_GROUP_ID
       value: "{{ KAFKA_CONSUMER_GROUP_ID }}"
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-soknad-pdfgen
