name: Lag avhengighetsgraf

on:
  push:
    branches:
      - main

jobs:
  dependency-submission:
    permissions:
      contents: write
    uses: navikt/hm-workflows/.github/workflows/dependency-submission.yaml@main
