name: Snyk scanning of dependencies
on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
      - Jenkinsfile
    branches:
      - main
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --configuration-attributes=usage:java-runtime --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git --org=hjelpemiddelbehov
